<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="26.556" timestamp="2022-10-18T16:27:29.328038" hostname="felurian"><testcase classname="tests.e2e.test_connections" name="test_oob_connect_via_public_did" time="26.450"><error message="failed on setup with &quot;Exception: ('Error creating issuer tenant', '{&quot;detail&quot;:&quot;Ledger request error. Request failed: client request invalid: UnauthorizedClientRequest(\'8NafWKTNYtwFCeFTdvcgZm\', 1666103272361635462, \'Not enough TRUSTEE signatures\').&quot;,&quot;stack&quot;:&quot;Traceback (most recent call last):\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py\\&quot;, line 159, in __call__\\n    await self.app(scope, receive, _send)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/starlette/exceptions.py\\&quot;, line 82, in __call__\\n    raise exc from None\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/starlette/exceptions.py\\&quot;, line 71, in __call__\\n    await self.app(scope, receive, sender)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/starlette/routing.py\\&quot;, line 580, in __call__\\n    await route.handle(scope, receive, send)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/starlette/routing.py\\&quot;, line 241, in handle\\n    await self.app(scope, receive, send)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/starlette/routing.py\\&quot;, line 52, in app\\n    response = await func(request)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/fastapi/routing.py\\&quot;, line 214, in app\\n    raw_response = await run_endpoint_function(\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/fastapi/routing.py\\&quot;, line 149, in run_endpoint_function\\n    return await dependant.call(**values)\\n  File \\&quot;/app/admin/tenants/tenants.py\\&quot;, line 79, in create_tenant\\n    onboard_result = await onboard_tenant(\\n  File \\&quot;/app/admin/tenants/onboarding.py\\&quot;, line 92, in onboard_tenant\\n    return await onboard_issuer(\\n  File \\&quot;/app/admin/tenants/onboarding.py\\&quot;, line 240, in onboard_issuer\\n    await endorser_controller.endorse_transaction.endorse_transaction(tran_id=end_txn.transaction_id)\\n  File \\&quot;/aries-cloudcontroller-python/aries_cloudcontroller/api/endorse_transaction.py\\&quot;, line 52, in endorse_transaction\\n    return await self.__endorse_transaction(\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\&quot;, line 38, in execute\\n    response = yield from executable.execute()\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\&quot;, line 20, in invoke\\n    response = yield from callback.on_failure(type(error), error, tb)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\&quot;, line 20, in invoke\\n    response = yield from callback.on_failure(type(error), error, tb)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\&quot;, line 20, in invoke\\n    response = yield from callback.on_failure(type(error), error, tb)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/execution.py\\&quot;, line 108, in on_failure\\n    return self._io.fail(exc_type, exc_val, exc_tb)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/execution.py\\&quot;, line 128, in fail\\n    return self._io.fail(exc_type, exc_val, exc_tb)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/interfaces.py\\&quot;, line 303, in fail\\n    compat.reraise(exc_type, exc_val, exc_tb)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/six.py\\&quot;, line 719, in reraise\\n    raise value\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\&quot;, line 17, in invoke\\n    response = yield from func(*args, **kwargs)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/hooks.py\\&quot;, line 109, in handle_exception\\n    compat.reraise(exc_type, exc_val, exc_tb)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/six.py\\&quot;, line 719, in reraise\\n    raise value\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\&quot;, line 17, in invoke\\n    response = yield from func(*args, **kwargs)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/hooks.py\\&quot;, line 109, in handle_exception\\n    compat.reraise(exc_type, exc_val, exc_tb)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/six.py\\&quot;, line 719, in reraise\\n    raise value\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\&quot;, line 17, in invoke\\n    response = yield from func(*args, **kwargs)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/uplink/clients/aiohttp_.py\\&quot;, line 135, in send\\n    response = yield from session.request(method, url, **extras)\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/aiohttp/client.py\\&quot;, line 643, in _request\\n    resp.raise_for_status()\\n  File \\&quot;/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py\\&quot;, line 1005, in raise_for_status\\n    raise ClientResponseError(\\naiohttp.client_exceptions.ClientResponseError: 400, message=\\&quot;Ledger request error. Request failed: client request invalid: UnauthorizedClientRequest(\'8NafWKTNYtwFCeFTdvcgZm\', 1666103272361635462, \'Not enough TRUSTEE signatures\').\\&quot;, url=URL(\'http://governance-ga-agent:3021/transactions/88ee9d4e-fed6-4e59-a272-268b6c7b8237/endorse\')\\n&quot;}')&quot;">args = (), kwargs = {}
request = &lt;SubRequest 'faber_client' for &lt;Function test_oob_connect_via_public_did&gt;&gt;
setup = &lt;function pytest_fixture_setup.&lt;locals&gt;.wrapper.&lt;locals&gt;.setup at 0x107b00d30&gt;
finalizer = &lt;function pytest_fixture_setup.&lt;locals&gt;.wrapper.&lt;locals&gt;.finalizer at 0x107b94dc0&gt;

    def wrapper(*args, **kwargs):
        loop = fixture_stripper.get_and_strip_from(
            FixtureStripper.EVENT_LOOP, kwargs
        )
        request = fixture_stripper.get_and_strip_from(
            FixtureStripper.REQUEST, kwargs
        )
    
        gen_obj = generator(*args, **kwargs)
    
        async def setup():
            res = await gen_obj.__anext__()
            return res
    
        def finalizer():
            """Yield again, to finalize."""
    
            async def async_finalizer():
                try:
                    await gen_obj.__anext__()
                except StopAsyncIteration:
                    pass
                else:
                    msg = "Async generator fixture didn't stop."
                    msg += "Yield only once."
                    raise ValueError(msg)
    
            loop.run_until_complete(async_finalizer())
    
        request.addfinalizer(finalizer)
&gt;       return loop.run_until_complete(setup())

../../.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytest_asyncio/plugin.py:142: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.pyenv/versions/3.8.10/lib/python3.8/asyncio/base_events.py:616: in run_until_complete
    return future.result()
../../.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytest_asyncio/plugin.py:123: in setup
    res = await gen_obj.__anext__()
app/tests/util/ecosystem_personas.py:32: in faber_client
    tenant = await create_issuer_tenant(client, "faber")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

tenant_admin_client = &lt;httpx.AsyncClient object at 0x107bfe1f0&gt;
name = 'faber'

    async def create_issuer_tenant(tenant_admin_client: AsyncClient, name: str):
        full_name = f"{name}{get_random_string(3)}"
        wallet_payload = {"name": full_name, "roles": ["issuer"]}
    
        wallet_response = await tenant_admin_client.post(
            "/admin/tenants", json=wallet_payload
        )
    
        if wallet_response.is_error:
&gt;           raise Exception("Error creating issuer tenant", wallet_response.text)
E           Exception: ('Error creating issuer tenant', '{"detail":"Ledger request error. Request failed: client request invalid: UnauthorizedClientRequest(\'8NafWKTNYtwFCeFTdvcgZm\', 1666103272361635462, \'Not enough TRUSTEE signatures\').","stack":"Traceback (most recent call last):\\n  File \\"/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py\\", line 159, in __call__\\n    await self.app(scope, receive, _send)\\n  File \\"/usr/local/lib/python3.8/site-packages/starlette/exceptions.py\\", line 82, in __call__\\n    raise exc from None\\n  File \\"/usr/local/lib/python3.8/site-packages/starlette/exceptions.py\\", line 71, in __call__\\n    await self.app(scope, receive, sender)\\n  File \\"/usr/local/lib/python3.8/site-packages/starlette/routing.py\\", line 580, in __call__\\n    await route.handle(scope, receive, send)\\n  File \\"/usr/local/lib/python3.8/site-packages/starlette/routing.py\\", line 241, in handle\\n    await self.app(scope, receive, send)\\n  File \\"/usr/local/lib/python3.8/site-packages/starlette/routing.py\\", line 52, in app\\n    response = await func(request)\\n  File \\"/usr/local/lib/python3.8/site-packages/fastapi/routing.py\\", line 214, in app\\n    raw_response = await run_endpoint_function(\\n  File \\"/usr/local/lib/python3.8/site-packages/fastapi/routing.py\\", line 149, in run_endpoint_function\\n    return await dependant.call(**values)\\n  File \\"/app/admin/tenants/tenants.py\\", line 79, in create_tenant\\n    onboard_result = await onboard_tenant(\\n  File \\"/app/admin/tenants/onboarding.py\\", line 92, in onboard_tenant\\n    return await onboard_issuer(\\n  File \\"/app/admin/tenants/onboarding.py\\", line 240, in onboard_issuer\\n    await endorser_controller.endorse_transaction.endorse_transaction(tran_id=end_txn.transaction_id)\\n  File \\"/aries-cloudcontroller-python/aries_cloudcontroller/api/endorse_transaction.py\\", line 52, in endorse_transaction\\n    return await self.__endorse_transaction(\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\", line 38, in execute\\n    response = yield from executable.execute()\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\", line 20, in invoke\\n    response = yield from callback.on_failure(type(error), error, tb)\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\", line 20, in invoke\\n    response = yield from callback.on_failure(type(error), error, tb)\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\", line 20, in invoke\\n    response = yield from callback.on_failure(type(error), error, tb)\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/execution.py\\", line 108, in on_failure\\n    return self._io.fail(exc_type, exc_val, exc_tb)\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/execution.py\\", line 128, in fail\\n    return self._io.fail(exc_type, exc_val, exc_tb)\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/interfaces.py\\", line 303, in fail\\n    compat.reraise(exc_type, exc_val, exc_tb)\\n  File \\"/usr/local/lib/python3.8/site-packages/six.py\\", line 719, in reraise\\n    raise value\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\", line 17, in invoke\\n    response = yield from func(*args, **kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/hooks.py\\", line 109, in handle_exception\\n    compat.reraise(exc_type, exc_val, exc_tb)\\n  File \\"/usr/local/lib/python3.8/site-packages/six.py\\", line 719, in reraise\\n    raise value\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\", line 17, in invoke\\n    response = yield from func(*args, **kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/hooks.py\\", line 109, in handle_exception\\n    compat.reraise(exc_type, exc_val, exc_tb)\\n  File \\"/usr/local/lib/python3.8/site-packages/six.py\\", line 719, in reraise\\n    raise value\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/io/asyncio_strategy.py\\", line 17, in invoke\\n    response = yield from func(*args, **kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/uplink/clients/aiohttp_.py\\", line 135, in send\\n    response = yield from session.request(method, url, **extras)\\n  File \\"/usr/local/lib/python3.8/site-packages/aiohttp/client.py\\", line 643, in _request\\n    resp.raise_for_status()\\n  File \\"/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py\\", line 1005, in raise_for_status\\n    raise ClientResponseError(\\naiohttp.client_exceptions.ClientResponseError: 400, message=\\"Ledger request error. Request failed: client request invalid: UnauthorizedClientRequest(\'8NafWKTNYtwFCeFTdvcgZm\', 1666103272361635462, \'Not enough TRUSTEE signatures\').\\", url=URL(\'http://governance-ga-agent:3021/transactions/88ee9d4e-fed6-4e59-a272-268b6c7b8237/endorse\')\\n"}')

app/tests/util/tenants.py:15: Exception</error></testcase></testsuite></testsuites>